find_path(CAENVME_INCLUDE_DIR libCAENVME.h /usr/include/ /usr/local/include ${CMAKE_SOURCE_DIR}/ModuleMode)
find_library(CAENVME_LIBRARY NAMES CAENVME PATHS /usr/lib/CAENVME /usr/local/lib/CAENVME ${CMAKE_SOURCE_DIR}/ModuleMode)

if (CAENVME_INCLUDE_DIR AND CAENVME_LIBRARY)
    set(CAENVME_FOUND TRUE)
endif (CAENVME_INCLUDE_DIR AND CAENVME_LIBRARY)
